---
version: '3'
networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    networks:
      - ros
    command: [roscore]

  rqt-bag:
    image: osrf/ros:noetic-desktop-full
    depends_on:
      - ros-master
    volumes:
      - /home/$USER:/home/$USER
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /media/$USER:/media/$USER
    user: $RQT_USER
    networks:
      - ros
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=rqt-bag
      - QT_X11_NO_MITSHM=1
    command: [rqt_bag]
