# https://hub.docker.com/r/cwaffles/openpose
FROM nvidia/cuda:10.0-cudnn7-devel

#get deps
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
python3-dev python3-pip git g++ wget make libprotobuf-dev protobuf-compiler libopencv-dev \
libgoogle-glog-dev libboost-all-dev libcaffe-cuda-dev libhdf5-dev libatlas-base-dev python3-setuptools

#for python api
RUN pip3 install --upgrade pip
RUN pip3 install numpy opencv-python tqdm scipy matplotlib

#replace cmake as old version has CUDA variable bugs
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz && \
    tar xzf cmake-3.16.0-Linux-x86_64.tar.gz -C /opt && \
    rm cmake-3.16.0-Linux-x86_64.tar.gz
ENV PATH="/opt/cmake-3.16.0-Linux-x86_64/bin:${PATH}"

#get openpose
WORKDIR /openpose
RUN git clone --depth 1 https://github.com/CMU-Perceptual-Computing-Lab/openpose.git .

#build it
WORKDIR /openpose/build
RUN cmake -DBUILD_PYTHON=ON .. && make -j `nproc`

WORKDIR /openpose/build

CMD mkdir scripts
#CMD mkdir scripts/output

WORKDIR /openpose

RUN pip3 install h5py

WORKDIR /openpose/build/scripts

COPY ./scripts/extractPoses.py ./
COPY ./scripts/process-hdf5.py ./
COPY ./scripts/extractDepth.py ./

CMD /bin/bash -c "cd /openpose/build/scripts && find /data -type f -name *.hdf5 -printf '%P' -exec ./process_hdf5.py {} \;"
